title: Mingyang Li's Homepage
page-top-title: Mingyang Li
top-section-bg-text: Marine Robotics and Control
home-subtitle: Mingyang Li&ensp;|&ensp;李明阳
copyright-text: '&copy; Mingyang Li 2023-2025. All Rights Reserved.'
